config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'home#index'
  
  resources :cryptos 
  resources :home 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crypto.rb
class Crypto < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cryptos_controller.rb
# class CryptosController < ApplicationController

#     def index 
#         @crypto = Crypto.new 
#     end 

#     def new  
#         @crypto = Crypto.new 
#     end 

#     def show 
#         @crypto = Crypto.find(params["crypto"][:id])
#     end 

# end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    
    def index 
       StartScrap.new.perform  
    end 

    def show
        Crypto.find(params[:id])
    end 




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crypto_helper.rb
module CryptoHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cryptos/index.html.erb
<h1>All currencies </h1>
<%= form_for @crypto do |f| %>

    <div class="field">
        <%= f.label :currency %><br />
        <%= f.collection_select :id, Crypto.order(:currency),:id,:currency, {include_blank: false}, {class: "form-control"} %>
    </div>

    <div>
        <%= f.submit %></div>
    </div>

<% end %>
























app/views/cryptos/show.html.erb
<p>  
        <br><%= @crypto.rates %></br>
    <%= link_to "Come back to the dropdownlist", cryptos_path %>
</p> 

app/views/home/index.html.erb
<div class="btn-group btn-input clearfix">
  <button type="button" class="btn btn-default dropdown-toggle form-control" data-toggle="dropdown">
    <span data-bind="label">Select a Currency</span> <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" role="menu">
	<% list = Crypto.all %>
	<% list.each do |hash| %>
      <li><a href ="home/<%=hash[:id]%>"><%=hash['currency']%></a></li>
    <% end %>
  </ul>
</div>







app/views/home/show.html.erb
<% monney = Crypto.find(params[:id]) %>
<%= monney['currency'] %>
<%= monney['rates'] %>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScrappeurOklm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified CSS --> 
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

  <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
  </head>




  </head>

  <body>
    <%= yield %>
  </body>
</html>